# Generated by Django 4.1.4 on 2023-01-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fechaDeEntrega',
            new_name='fecha_de_entrega',
        ),
    ]
